---
version: '2'
services:

  vote:
    build: ./vote/
    ports: 
      - 31000:80
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result/
    ports: 
      - 31001:80
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker/
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: redis:alpine
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:

